using  Day14_Stack_Queue;
Console.WriteLine("Welcome to the stack problem");
CreatIngStack linkedListStack = new CreatIngStack();
linkedListStack.Push(70);
linkedListStack.Push(30);
linkedListStack.Push(56);
linkedListStack.Display();
linkedListStack.Peek();
linkedListStack.Pop();
linkedListStack.IsEmpty();
linkedListStack.Display();